services:
  hyperf:
    container_name: hyperf-skeleton
    image: hyperf-skeleton
    user: 1000:1000
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

  mariadb:
    image: mariadb:11.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=myapi

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"

networks:
  default:
    name: hyperf-skeleton
